name: Unit test

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      # ~~~~~~~~~~~~~ Java setup ~~~~~~~~~~~~~
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'
      - name: Display Java version
        run: java --version
        
      # ~~~~~~~~~~~~~ Test ~~~~~~~~~~~~~
      - name: Run gradle tests
        run: ./gradlew test
